# A generic, single database configuration for Alembic.

[alembic]
# path to migration script directory
script_location = alembic

# template used to generate migration file names; The default value is %%(rev)s_%%(slug)s
file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present.
# defaults to the current working directory.
prepend_sys_path = .

# timezone to use when rendering the date within the migration file as well as the filename.
# string value is passed to dateutil.tz.gettz()
timezone = UTC

# max length of characters in --slug
# slug_length = 40

[post_write_hooks]

[logging]
default_handler = stream

[loggers]
keys = root,alembic,sqlalchemy

[handlers]
keys = stream

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = stream
qualname =

[logger_alembic]
level = INFO
handlers = stream
qualname = alembic

[logger_sqlalchemy]
level = WARN
handlers = stream
qualname = sqlalchemy.engine

[handler_stream]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
